### ISSUE TITLE
Receiving 'Bad credentials' on organisation repository.

### ISSUE THREAD

**Issue by lnicolet** [rowi1de/auto-assign-review-teams#32]
I'm receiving this error
```
(node:1494) UnhandledPromiseRejectionWarning: HttpError: Bad credentials
    at /home/runner/work/_actions/rowi1de/auto-assign-review-teams/v.1.0.1/lib/index.js:8062:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    (node:1494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Bad credentials
```

When trying to run the action to automatically assign a team on each PR created.
Here's my `team-assigner.yaml` file
```yaml
name: "Assign Reviewers"

on:
  pull_request:
    branches:
      - 'develop'
      - 'release/**'
     
jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign team review"
      uses: rowi1de/auto-assign-review-teams@v.1.0.1
      with:
        repo-token: ${{ secrets.TEAM_ASSIGNER_TOKEN }}
        teams: "team_name"
        skip-with-manual-reviewers: 3
```

`TEAM_ASSIGNER_TOKEN` is listed in the `Repository tokens` in the repository settings tab.
